export const COMMUNITY_EVENT_KIND = 34550;

export const COMMUNITIES_LIST_EVENT_KIND = 10004;

export const MEMBERS_SET_EVENT_KIND = 30001;

export const CHANNEL_EVENT_KIND = 40;

export const CHANNEL_METADATA_EVENT_KIND = 41;

export const MESSAGE_EVENT_KIND = 42;

export const HIDE_MESSAGE_EVENT_KIND = 43;

export const MUTE_USER_EVENT_KIND = 44;

export const LINKS_SET_EVENT_KIND = 30003;
