export const COMMUNITY_EVENT_KIND = 34550;

export const COMMUNITIES_LIST_EVENT_KIND = 10004;

export const MEMBERS_SET_EVENT_KIND = 30001;

export const CHANNEL_EVENT_KIND = 40;

export const CHANNEL_METADATA_EVENT_KIND = 41;

export const LINKS_SET_EVENT_KIND = 30003;
